#!/bin/sh
PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

fey="39 44"
gate39="33825 193.115.214.218 10.251.14.119"
gate44="44569 96.112.125.108 46.163.88.20"

gnip()
{
! ping -I nwg$1 -s0 -qc1 -W1 $2 >/dev/null 2>&1
}

for i in $fey; do ip a s nwg$i | grep -q UP || continue
    gate=$(eval echo \$gate$i)
    pgat="$i ${gate##* }"
    if gnip $pgat && gnip $pgat && gnip $pgat; then
        port=$(awk 'BEGIN{srand();print int(rand()*(63000-2000))+2000}')
        while netstat -nlu | grep -qw $port
        do
            port=$(awk 'BEGIN{srand();print int(rand()*(63000-2000))+2000}')
        done
        nping --udp --count 8 --source-port $port --data-length 64 --dest-port ${gate% *} >/dev/null 2>&1
        ndmc -c "interface Wireguard$i wireguard listen-port $port" >/dev/null 2>&1
    fi
done >/dev/null 2>&1
