#!/bin/sh
PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

gnip()
{
! ping -I nwg$1 -s0 -qc1 -W1 1.1.1.1 >/dev/null 2>&1
}

for i in $(ip a | sed -n 's/.*nwg\(.*\): <.*UP.*/\1/p'); do
 rem=$(echo $(ndmc -c "show interface Wireguard$i" | sed -n 's/.*remote.*: \(.*\)/\1/p'))
 echo $rem | grep -q '^0\| 0' && continue
 if gnip $i && gnip $i && gnip $i && gnip $i; then
  port=$(awk 'BEGIN{srand();print int(rand()*63000)+2000}')
  while netstat -nlu | grep -qw $port; do
   port=$(awk 'BEGIN{srand();print int(rand()*63000)+2000}')
  done >/dev/null 2>&1
  nping --udp --count 9 --source-port $port --data-length 64 --dest-port $(echo $rem | cut -f2 -d' ') ${rem%% *} >/dev/null 2>&1
  ndmc -c "interface Wireguard$i wireguard listen-port $port" >/dev/null 2>&1
 fi
done
